version: '3'
services:
  process-nginx:
    build:
      context: ./process/docker
      dockerfile: nginx.docker
    volumes:
      - ./process:/var/www/process
    ports:
      - "8081:80"
  process-php-fpm:
    build:
      context: ./process/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./process:/var/www/process
  process-php-cli:
    build:
      context: ./process/docker
      dockerfile: php-cli.docker
    volumes:
      - ./process:/var/www/process
    working_dir: /var/www/process
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
